stages:
  - publish
  
ci_test:
  stage: publish
  tags:
    - el8
    - oms
    - client
    - api
  only:
    - master
  script:
    - echo "$CI_DEPLOY_TOKEN_USERNAME"
    - echo "$CI_DEPLOY_TOKEN_PWD"
    - echo "$CI_PROJECT_ID"


deploy_master_tag:
  stage: publish
  tags:
    - el8
    - oms
    - client
    - api
  only:
    - tags
  script:
    - ./kojitag.sh
    - echo "$CI_DEPLOY_TOKEN_USERNAME"
    - echo "$CI_DEPLOY_TOKEN_PWD"
    - echo "$CI_PROJECT_ID"
    - /usr/bin/sed -i "s/CI_DEPLOY_TOKEN_USERNAME/${env.CI_DEPLOY_TOKEN_USERNAME}/g" .pypirc
    - /usr/bin/sed -i "s/CI_DEPLOY_TOKEN_PWD/${env.CI_DEPLOY_TOKEN_PWD}/g" .pypirc
    - cp .pypirc ~/
    - ./publish_pypi.sh

