stages:
  - publish
  

deploy_master_tag:
  stage: publish
  tags:
    - el8
    - oms
    - client
    - api
  only:
    - tags
  script:
    - ./kojitag.sh
    - echo "${env.CI_DEPLOY_TOKEN_USERNAME}"
    - echo "${env.CI_DEPLOY_TOKEN_PWD}"
    - echo "${env.env.CI_PROJECT_ID}"
    - /usr/bin/sed -i "s/CI_DEPLOY_TOKEN_USERNAME/${env.CI_DEPLOY_TOKEN_USERNAME}/g" .pypirc
    - /usr/bin/sed -i "s/CI_DEPLOY_TOKEN_PWD/${env.CI_DEPLOY_TOKEN_PWD}/g" .pypirc
    - cp .pypirc ~/
    - ./publish_pypi.sh

